#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Tour.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_TourDL")]
	public partial class QL_TourDLichDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChauLuc(ChauLuc instance);
    partial void UpdateChauLuc(ChauLuc instance);
    partial void DeleteChauLuc(ChauLuc instance);
    partial void InsertPHUONGTIEN(PHUONGTIEN instance);
    partial void UpdatePHUONGTIEN(PHUONGTIEN instance);
    partial void DeletePHUONGTIEN(PHUONGTIEN instance);
    partial void InsertCTHinhTour(CTHinhTour instance);
    partial void UpdateCTHinhTour(CTHinhTour instance);
    partial void DeleteCTHinhTour(CTHinhTour instance);
    partial void InsertDATTOUR(DATTOUR instance);
    partial void UpdateDATTOUR(DATTOUR instance);
    partial void DeleteDATTOUR(DATTOUR instance);
    partial void InsertDIEMDEN(DIEMDEN instance);
    partial void UpdateDIEMDEN(DIEMDEN instance);
    partial void DeleteDIEMDEN(DIEMDEN instance);
    partial void InsertHUONGDANVIEN(HUONGDANVIEN instance);
    partial void UpdateHUONGDANVIEN(HUONGDANVIEN instance);
    partial void DeleteHUONGDANVIEN(HUONGDANVIEN instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertKHACHSAN(KHACHSAN instance);
    partial void UpdateKHACHSAN(KHACHSAN instance);
    partial void DeleteKHACHSAN(KHACHSAN instance);
    partial void InsertMIEN(MIEN instance);
    partial void UpdateMIEN(MIEN instance);
    partial void DeleteMIEN(MIEN instance);
    partial void InsertTOUR(TOUR instance);
    partial void UpdateTOUR(TOUR instance);
    partial void DeleteTOUR(TOUR instance);
    #endregion
		
		public QL_TourDLichDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_TourDLConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TourDLichDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TourDLichDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TourDLichDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TourDLichDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChauLuc> ChauLucs
		{
			get
			{
				return this.GetTable<ChauLuc>();
			}
		}
		
		public System.Data.Linq.Table<PHUONGTIEN> PHUONGTIENs
		{
			get
			{
				return this.GetTable<PHUONGTIEN>();
			}
		}
		
		public System.Data.Linq.Table<CTHinhTour> CTHinhTours
		{
			get
			{
				return this.GetTable<CTHinhTour>();
			}
		}
		
		public System.Data.Linq.Table<DATTOUR> DATTOURs
		{
			get
			{
				return this.GetTable<DATTOUR>();
			}
		}
		
		public System.Data.Linq.Table<DIEMDEN> DIEMDENs
		{
			get
			{
				return this.GetTable<DIEMDEN>();
			}
		}
		
		public System.Data.Linq.Table<HUONGDANVIEN> HUONGDANVIENs
		{
			get
			{
				return this.GetTable<HUONGDANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<KHACHSAN> KHACHSANs
		{
			get
			{
				return this.GetTable<KHACHSAN>();
			}
		}
		
		public System.Data.Linq.Table<MIEN> MIENs
		{
			get
			{
				return this.GetTable<MIEN>();
			}
		}
		
		public System.Data.Linq.Table<TOUR> TOURs
		{
			get
			{
				return this.GetTable<TOUR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChauLuc")]
	public partial class ChauLuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChauLuc;
		
		private string _TenChauLuc;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChauLucChanging(int value);
    partial void OnMaChauLucChanged();
    partial void OnTenChauLucChanging(string value);
    partial void OnTenChauLucChanged();
    #endregion
		
		public ChauLuc()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChauLuc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaChauLuc
		{
			get
			{
				return this._MaChauLuc;
			}
			set
			{
				if ((this._MaChauLuc != value))
				{
					this.OnMaChauLucChanging(value);
					this.SendPropertyChanging();
					this._MaChauLuc = value;
					this.SendPropertyChanged("MaChauLuc");
					this.OnMaChauLucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChauLuc", DbType="NVarChar(50)")]
		public string TenChauLuc
		{
			get
			{
				return this._TenChauLuc;
			}
			set
			{
				if ((this._TenChauLuc != value))
				{
					this.OnTenChauLucChanging(value);
					this.SendPropertyChanging();
					this._TenChauLuc = value;
					this.SendPropertyChanged("TenChauLuc");
					this.OnTenChauLucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChauLuc_TOUR", Storage="_TOURs", ThisKey="MaChauLuc", OtherKey="MaChauLuc")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.ChauLuc = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.ChauLuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHUONGTIEN")]
	public partial class PHUONGTIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPT;
		
		private string _TenPT;
		
		private string _ghichu;
		
		private string _HinhAnh;
		
		private string _MoTa;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPTChanging(int value);
    partial void OnMaPTChanged();
    partial void OnTenPTChanging(string value);
    partial void OnTenPTChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public PHUONGTIEN()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPT
		{
			get
			{
				return this._MaPT;
			}
			set
			{
				if ((this._MaPT != value))
				{
					this.OnMaPTChanging(value);
					this.SendPropertyChanging();
					this._MaPT = value;
					this.SendPropertyChanged("MaPT");
					this.OnMaPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPT", DbType="NVarChar(MAX)")]
		public string TenPT
		{
			get
			{
				return this._TenPT;
			}
			set
			{
				if ((this._TenPT != value))
				{
					this.OnTenPTChanging(value);
					this.SendPropertyChanging();
					this._TenPT = value;
					this.SendPropertyChanged("TenPT");
					this.OnTenPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(MAX)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONGTIEN_TOUR", Storage="_TOURs", ThisKey="MaPT", OtherKey="MaPT")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHUONGTIEN = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHUONGTIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHinhTour")]
	public partial class CTHinhTour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTour;
		
		private string _Hinh1;
		
		private string _Hinh2;
		
		private string _Hinh3;
		
		private string _Hinh4;
		
		private string _Hinh5;
		
		private string _Hinh6;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTourChanging(int value);
    partial void OnMaTourChanged();
    partial void OnHinh1Changing(string value);
    partial void OnHinh1Changed();
    partial void OnHinh2Changing(string value);
    partial void OnHinh2Changed();
    partial void OnHinh3Changing(string value);
    partial void OnHinh3Changed();
    partial void OnHinh4Changing(string value);
    partial void OnHinh4Changed();
    partial void OnHinh5Changing(string value);
    partial void OnHinh5Changed();
    partial void OnHinh6Changing(string value);
    partial void OnHinh6Changed();
    #endregion
		
		public CTHinhTour()
		{
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh1", DbType="NVarChar(MAX)")]
		public string Hinh1
		{
			get
			{
				return this._Hinh1;
			}
			set
			{
				if ((this._Hinh1 != value))
				{
					this.OnHinh1Changing(value);
					this.SendPropertyChanging();
					this._Hinh1 = value;
					this.SendPropertyChanged("Hinh1");
					this.OnHinh1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh2", DbType="NVarChar(MAX)")]
		public string Hinh2
		{
			get
			{
				return this._Hinh2;
			}
			set
			{
				if ((this._Hinh2 != value))
				{
					this.OnHinh2Changing(value);
					this.SendPropertyChanging();
					this._Hinh2 = value;
					this.SendPropertyChanged("Hinh2");
					this.OnHinh2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh3", DbType="NVarChar(MAX)")]
		public string Hinh3
		{
			get
			{
				return this._Hinh3;
			}
			set
			{
				if ((this._Hinh3 != value))
				{
					this.OnHinh3Changing(value);
					this.SendPropertyChanging();
					this._Hinh3 = value;
					this.SendPropertyChanged("Hinh3");
					this.OnHinh3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh4", DbType="NVarChar(MAX)")]
		public string Hinh4
		{
			get
			{
				return this._Hinh4;
			}
			set
			{
				if ((this._Hinh4 != value))
				{
					this.OnHinh4Changing(value);
					this.SendPropertyChanging();
					this._Hinh4 = value;
					this.SendPropertyChanged("Hinh4");
					this.OnHinh4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh5", DbType="NVarChar(MAX)")]
		public string Hinh5
		{
			get
			{
				return this._Hinh5;
			}
			set
			{
				if ((this._Hinh5 != value))
				{
					this.OnHinh5Changing(value);
					this.SendPropertyChanging();
					this._Hinh5 = value;
					this.SendPropertyChanged("Hinh5");
					this.OnHinh5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh6", DbType="NVarChar(MAX)")]
		public string Hinh6
		{
			get
			{
				return this._Hinh6;
			}
			set
			{
				if ((this._Hinh6 != value))
				{
					this.OnHinh6Changing(value);
					this.SendPropertyChanging();
					this._Hinh6 = value;
					this.SendPropertyChanged("Hinh6");
					this.OnHinh6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CTHinhTour", Storage="_TOUR", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.CTHinhTour = null;
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.CTHinhTour = this;
						this._MaTour = value.MaTour;
					}
					else
					{
						this._MaTour = default(int);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATTOUR")]
	public partial class DATTOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTour;
		
		private int _MaKH;
		
		private int _MaHDV;
		
		private System.Nullable<int> _SoLuongNguoiLon;
		
		private System.Nullable<int> _SoLuongTreEm;
		
		private string _YeuCauThem;
		
		private System.Nullable<System.DateTime> _NgayBD;
		
		private System.Nullable<double> _thanhTien;
		
		private EntityRef<HUONGDANVIEN> _HUONGDANVIEN;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTourChanging(int value);
    partial void OnMaTourChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnMaHDVChanging(int value);
    partial void OnMaHDVChanged();
    partial void OnSoLuongNguoiLonChanging(System.Nullable<int> value);
    partial void OnSoLuongNguoiLonChanged();
    partial void OnSoLuongTreEmChanging(System.Nullable<int> value);
    partial void OnSoLuongTreEmChanged();
    partial void OnYeuCauThemChanging(string value);
    partial void OnYeuCauThemChanged();
    partial void OnNgayBDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBDChanged();
    partial void OnthanhTienChanging(System.Nullable<double> value);
    partial void OnthanhTienChanged();
    #endregion
		
		public DATTOUR()
		{
			this._HUONGDANVIEN = default(EntityRef<HUONGDANVIEN>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHDV
		{
			get
			{
				return this._MaHDV;
			}
			set
			{
				if ((this._MaHDV != value))
				{
					if (this._HUONGDANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDVChanging(value);
					this.SendPropertyChanging();
					this._MaHDV = value;
					this.SendPropertyChanged("MaHDV");
					this.OnMaHDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongNguoiLon", DbType="Int")]
		public System.Nullable<int> SoLuongNguoiLon
		{
			get
			{
				return this._SoLuongNguoiLon;
			}
			set
			{
				if ((this._SoLuongNguoiLon != value))
				{
					this.OnSoLuongNguoiLonChanging(value);
					this.SendPropertyChanging();
					this._SoLuongNguoiLon = value;
					this.SendPropertyChanged("SoLuongNguoiLon");
					this.OnSoLuongNguoiLonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTreEm", DbType="Int")]
		public System.Nullable<int> SoLuongTreEm
		{
			get
			{
				return this._SoLuongTreEm;
			}
			set
			{
				if ((this._SoLuongTreEm != value))
				{
					this.OnSoLuongTreEmChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTreEm = value;
					this.SendPropertyChanged("SoLuongTreEm");
					this.OnSoLuongTreEmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauThem", DbType="NVarChar(MAX)")]
		public string YeuCauThem
		{
			get
			{
				return this._YeuCauThem;
			}
			set
			{
				if ((this._YeuCauThem != value))
				{
					this.OnYeuCauThemChanging(value);
					this.SendPropertyChanging();
					this._YeuCauThem = value;
					this.SendPropertyChanged("YeuCauThem");
					this.OnYeuCauThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBD", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBD
		{
			get
			{
				return this._NgayBD;
			}
			set
			{
				if ((this._NgayBD != value))
				{
					this.OnNgayBDChanging(value);
					this.SendPropertyChanging();
					this._NgayBD = value;
					this.SendPropertyChanged("NgayBD");
					this.OnNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Float")]
		public System.Nullable<double> thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HUONGDANVIEN_DATTOUR", Storage="_HUONGDANVIEN", ThisKey="MaHDV", OtherKey="MaHDV", IsForeignKey=true)]
		public HUONGDANVIEN HUONGDANVIEN
		{
			get
			{
				return this._HUONGDANVIEN.Entity;
			}
			set
			{
				HUONGDANVIEN previousValue = this._HUONGDANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._HUONGDANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HUONGDANVIEN.Entity = null;
						previousValue.DATTOURs.Remove(this);
					}
					this._HUONGDANVIEN.Entity = value;
					if ((value != null))
					{
						value.DATTOURs.Add(this);
						this._MaHDV = value.MaHDV;
					}
					else
					{
						this._MaHDV = default(int);
					}
					this.SendPropertyChanged("HUONGDANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DATTOUR", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.DATTOURs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.DATTOURs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_DATTOUR", Storage="_TOUR", ThisKey="MaTour", OtherKey="MaTour", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.DATTOURs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.DATTOURs.Add(this);
						this._MaTour = value.MaTour;
					}
					else
					{
						this._MaTour = default(int);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIEMDEN")]
	public partial class DIEMDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDD;
		
		private string _TenDD;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDDChanging(int value);
    partial void OnMaDDChanged();
    partial void OnTenDDChanging(string value);
    partial void OnTenDDChanged();
    #endregion
		
		public DIEMDEN()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDD
		{
			get
			{
				return this._MaDD;
			}
			set
			{
				if ((this._MaDD != value))
				{
					this.OnMaDDChanging(value);
					this.SendPropertyChanging();
					this._MaDD = value;
					this.SendPropertyChanged("MaDD");
					this.OnMaDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDD", DbType="NVarChar(MAX)")]
		public string TenDD
		{
			get
			{
				return this._TenDD;
			}
			set
			{
				if ((this._TenDD != value))
				{
					this.OnTenDDChanging(value);
					this.SendPropertyChanging();
					this._TenDD = value;
					this.SendPropertyChanged("TenDD");
					this.OnTenDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMDEN_TOUR", Storage="_TOURs", ThisKey="MaDD", OtherKey="MaDD")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.DIEMDEN = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.DIEMDEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HUONGDANVIEN")]
	public partial class HUONGDANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHDV;
		
		private string _TenHDV;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private System.Nullable<int> _SDT;
		
		private System.Nullable<int> _CMND;
		
		private string _QuocTich;
		
		private EntitySet<DATTOUR> _DATTOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDVChanging(int value);
    partial void OnMaHDVChanged();
    partial void OnTenHDVChanging(string value);
    partial void OnTenHDVChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    partial void OnCMNDChanging(System.Nullable<int> value);
    partial void OnCMNDChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    #endregion
		
		public HUONGDANVIEN()
		{
			this._DATTOURs = new EntitySet<DATTOUR>(new Action<DATTOUR>(this.attach_DATTOURs), new Action<DATTOUR>(this.detach_DATTOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHDV
		{
			get
			{
				return this._MaHDV;
			}
			set
			{
				if ((this._MaHDV != value))
				{
					this.OnMaHDVChanging(value);
					this.SendPropertyChanging();
					this._MaHDV = value;
					this.SendPropertyChanged("MaHDV");
					this.OnMaHDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHDV", DbType="NVarChar(MAX)")]
		public string TenHDV
		{
			get
			{
				return this._TenHDV;
			}
			set
			{
				if ((this._TenHDV != value))
				{
					this.OnTenHDVChanging(value);
					this.SendPropertyChanging();
					this._TenHDV = value;
					this.SendPropertyChanged("TenHDV");
					this.OnTenHDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int")]
		public System.Nullable<int> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(50)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HUONGDANVIEN_DATTOUR", Storage="_DATTOURs", ThisKey="MaHDV", OtherKey="MaHDV")]
		public EntitySet<DATTOUR> DATTOURs
		{
			get
			{
				return this._DATTOURs;
			}
			set
			{
				this._DATTOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATTOURs(DATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.HUONGDANVIEN = this;
		}
		
		private void detach_DATTOURs(DATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.HUONGDANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _TenDN;
		
		private string _MatKhau;
		
		private string _TenKH;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<int> _CMND;
		
		private string _QuocTich;
		
		private string _SDT;
		
		private string _Email;
		
		private EntitySet<DATTOUR> _DATTOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnCMNDChanging(System.Nullable<int> value);
    partial void OnCMNDChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._DATTOURs = new EntitySet<DATTOUR>(new Action<DATTOUR>(this.attach_DATTOURs), new Action<DATTOUR>(this.detach_DATTOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="Char(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(MAX)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int")]
		public System.Nullable<int> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(MAX)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DATTOUR", Storage="_DATTOURs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DATTOUR> DATTOURs
		{
			get
			{
				return this._DATTOURs;
			}
			set
			{
				this._DATTOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATTOURs(DATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_DATTOURs(DATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHSAN")]
	public partial class KHACHSAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKS;
		
		private string _TenKS;
		
		private string _DiaChi;
		
		private System.Nullable<int> _SDT;
		
		private string _HinhAnh;
		
		private string _MoTa;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKSChanging(int value);
    partial void OnMaKSChanged();
    partial void OnTenKSChanging(string value);
    partial void OnTenKSChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public KHACHSAN()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKS", DbType="NVarChar(MAX)")]
		public string TenKS
		{
			get
			{
				return this._TenKS;
			}
			set
			{
				if ((this._TenKS != value))
				{
					this.OnTenKSChanging(value);
					this.SendPropertyChanging();
					this._TenKS = value;
					this.SendPropertyChanged("TenKS");
					this.OnTenKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHSAN_TOUR", Storage="_TOURs", ThisKey="MaKS", OtherKey="MaKS")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHSAN = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHSAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MIEN")]
	public partial class MIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMien;
		
		private string _TenMien;
		
		private string _HinhAnh;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMienChanging(int value);
    partial void OnMaMienChanged();
    partial void OnTenMienChanging(string value);
    partial void OnTenMienChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    #endregion
		
		public MIEN()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaMien
		{
			get
			{
				return this._MaMien;
			}
			set
			{
				if ((this._MaMien != value))
				{
					this.OnMaMienChanging(value);
					this.SendPropertyChanging();
					this._MaMien = value;
					this.SendPropertyChanged("MaMien");
					this.OnMaMienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMien", DbType="NVarChar(MAX)")]
		public string TenMien
		{
			get
			{
				return this._TenMien;
			}
			set
			{
				if ((this._TenMien != value))
				{
					this.OnTenMienChanging(value);
					this.SendPropertyChanging();
					this._TenMien = value;
					this.SendPropertyChanged("TenMien");
					this.OnTenMienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MIEN_TOUR", Storage="_TOURs", ThisKey="MaMien", OtherKey="MaMien")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.MIEN = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.MIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOUR")]
	public partial class TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTour;
		
		private string _TenTour;
		
		private System.Nullable<int> _SoNgay;
		
		private System.Nullable<int> _MaMien;
		
		private System.Nullable<int> _MaChauLuc;
		
		private System.Nullable<int> _MaDD;
		
		private string _HinhAnh;
		
		private System.Nullable<decimal> _Gia;
		
		private System.Nullable<int> _SoLuongKhach;
		
		private System.Nullable<int> _MaKS;
		
		private System.Nullable<int> _MaPT;
		
		private string _MoTa;
		
		private EntityRef<CTHinhTour> _CTHinhTour;
		
		private EntitySet<DATTOUR> _DATTOURs;
		
		private EntityRef<ChauLuc> _ChauLuc;
		
		private EntityRef<DIEMDEN> _DIEMDEN;
		
		private EntityRef<KHACHSAN> _KHACHSAN;
		
		private EntityRef<MIEN> _MIEN;
		
		private EntityRef<PHUONGTIEN> _PHUONGTIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTourChanging(int value);
    partial void OnMaTourChanged();
    partial void OnTenTourChanging(string value);
    partial void OnTenTourChanged();
    partial void OnSoNgayChanging(System.Nullable<int> value);
    partial void OnSoNgayChanged();
    partial void OnMaMienChanging(System.Nullable<int> value);
    partial void OnMaMienChanged();
    partial void OnMaChauLucChanging(System.Nullable<int> value);
    partial void OnMaChauLucChanged();
    partial void OnMaDDChanging(System.Nullable<int> value);
    partial void OnMaDDChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    partial void OnSoLuongKhachChanging(System.Nullable<int> value);
    partial void OnSoLuongKhachChanged();
    partial void OnMaKSChanging(System.Nullable<int> value);
    partial void OnMaKSChanged();
    partial void OnMaPTChanging(System.Nullable<int> value);
    partial void OnMaPTChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public TOUR()
		{
			this._CTHinhTour = default(EntityRef<CTHinhTour>);
			this._DATTOURs = new EntitySet<DATTOUR>(new Action<DATTOUR>(this.attach_DATTOURs), new Action<DATTOUR>(this.detach_DATTOURs));
			this._ChauLuc = default(EntityRef<ChauLuc>);
			this._DIEMDEN = default(EntityRef<DIEMDEN>);
			this._KHACHSAN = default(EntityRef<KHACHSAN>);
			this._MIEN = default(EntityRef<MIEN>);
			this._PHUONGTIEN = default(EntityRef<PHUONGTIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTour", DbType="NVarChar(MAX)")]
		public string TenTour
		{
			get
			{
				return this._TenTour;
			}
			set
			{
				if ((this._TenTour != value))
				{
					this.OnTenTourChanging(value);
					this.SendPropertyChanging();
					this._TenTour = value;
					this.SendPropertyChanged("TenTour");
					this.OnTenTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgay", DbType="Int")]
		public System.Nullable<int> SoNgay
		{
			get
			{
				return this._SoNgay;
			}
			set
			{
				if ((this._SoNgay != value))
				{
					this.OnSoNgayChanging(value);
					this.SendPropertyChanging();
					this._SoNgay = value;
					this.SendPropertyChanged("SoNgay");
					this.OnSoNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMien", DbType="Int")]
		public System.Nullable<int> MaMien
		{
			get
			{
				return this._MaMien;
			}
			set
			{
				if ((this._MaMien != value))
				{
					if (this._MIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMienChanging(value);
					this.SendPropertyChanging();
					this._MaMien = value;
					this.SendPropertyChanged("MaMien");
					this.OnMaMienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChauLuc", DbType="Int")]
		public System.Nullable<int> MaChauLuc
		{
			get
			{
				return this._MaChauLuc;
			}
			set
			{
				if ((this._MaChauLuc != value))
				{
					if (this._ChauLuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChauLucChanging(value);
					this.SendPropertyChanging();
					this._MaChauLuc = value;
					this.SendPropertyChanged("MaChauLuc");
					this.OnMaChauLucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDD", DbType="Int")]
		public System.Nullable<int> MaDD
		{
			get
			{
				return this._MaDD;
			}
			set
			{
				if ((this._MaDD != value))
				{
					if (this._DIEMDEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDDChanging(value);
					this.SendPropertyChanging();
					this._MaDD = value;
					this.SendPropertyChanged("MaDD");
					this.OnMaDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongKhach", DbType="Int")]
		public System.Nullable<int> SoLuongKhach
		{
			get
			{
				return this._SoLuongKhach;
			}
			set
			{
				if ((this._SoLuongKhach != value))
				{
					this.OnSoLuongKhachChanging(value);
					this.SendPropertyChanging();
					this._SoLuongKhach = value;
					this.SendPropertyChanged("SoLuongKhach");
					this.OnSoLuongKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKS", DbType="Int")]
		public System.Nullable<int> MaKS
		{
			get
			{
				return this._MaKS;
			}
			set
			{
				if ((this._MaKS != value))
				{
					if (this._KHACHSAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKSChanging(value);
					this.SendPropertyChanging();
					this._MaKS = value;
					this.SendPropertyChanged("MaKS");
					this.OnMaKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPT", DbType="Int")]
		public System.Nullable<int> MaPT
		{
			get
			{
				return this._MaPT;
			}
			set
			{
				if ((this._MaPT != value))
				{
					if (this._PHUONGTIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPTChanging(value);
					this.SendPropertyChanging();
					this._MaPT = value;
					this.SendPropertyChanged("MaPT");
					this.OnMaPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CTHinhTour", Storage="_CTHinhTour", ThisKey="MaTour", OtherKey="MaTour", IsUnique=true, IsForeignKey=false)]
		public CTHinhTour CTHinhTour
		{
			get
			{
				return this._CTHinhTour.Entity;
			}
			set
			{
				CTHinhTour previousValue = this._CTHinhTour.Entity;
				if (((previousValue != value) 
							|| (this._CTHinhTour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CTHinhTour.Entity = null;
						previousValue.TOUR = null;
					}
					this._CTHinhTour.Entity = value;
					if ((value != null))
					{
						value.TOUR = this;
					}
					this.SendPropertyChanged("CTHinhTour");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_DATTOUR", Storage="_DATTOURs", ThisKey="MaTour", OtherKey="MaTour")]
		public EntitySet<DATTOUR> DATTOURs
		{
			get
			{
				return this._DATTOURs;
			}
			set
			{
				this._DATTOURs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChauLuc_TOUR", Storage="_ChauLuc", ThisKey="MaChauLuc", OtherKey="MaChauLuc", IsForeignKey=true)]
		public ChauLuc ChauLuc
		{
			get
			{
				return this._ChauLuc.Entity;
			}
			set
			{
				ChauLuc previousValue = this._ChauLuc.Entity;
				if (((previousValue != value) 
							|| (this._ChauLuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChauLuc.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._ChauLuc.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._MaChauLuc = value.MaChauLuc;
					}
					else
					{
						this._MaChauLuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChauLuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEMDEN_TOUR", Storage="_DIEMDEN", ThisKey="MaDD", OtherKey="MaDD", IsForeignKey=true)]
		public DIEMDEN DIEMDEN
		{
			get
			{
				return this._DIEMDEN.Entity;
			}
			set
			{
				DIEMDEN previousValue = this._DIEMDEN.Entity;
				if (((previousValue != value) 
							|| (this._DIEMDEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIEMDEN.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._DIEMDEN.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._MaDD = value.MaDD;
					}
					else
					{
						this._MaDD = default(Nullable<int>);
					}
					this.SendPropertyChanged("DIEMDEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHSAN_TOUR", Storage="_KHACHSAN", ThisKey="MaKS", OtherKey="MaKS", IsForeignKey=true)]
		public KHACHSAN KHACHSAN
		{
			get
			{
				return this._KHACHSAN.Entity;
			}
			set
			{
				KHACHSAN previousValue = this._KHACHSAN.Entity;
				if (((previousValue != value) 
							|| (this._KHACHSAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHSAN.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._KHACHSAN.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._MaKS = value.MaKS;
					}
					else
					{
						this._MaKS = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACHSAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MIEN_TOUR", Storage="_MIEN", ThisKey="MaMien", OtherKey="MaMien", IsForeignKey=true)]
		public MIEN MIEN
		{
			get
			{
				return this._MIEN.Entity;
			}
			set
			{
				MIEN previousValue = this._MIEN.Entity;
				if (((previousValue != value) 
							|| (this._MIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MIEN.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._MIEN.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._MaMien = value.MaMien;
					}
					else
					{
						this._MaMien = default(Nullable<int>);
					}
					this.SendPropertyChanged("MIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONGTIEN_TOUR", Storage="_PHUONGTIEN", ThisKey="MaPT", OtherKey="MaPT", IsForeignKey=true)]
		public PHUONGTIEN PHUONGTIEN
		{
			get
			{
				return this._PHUONGTIEN.Entity;
			}
			set
			{
				PHUONGTIEN previousValue = this._PHUONGTIEN.Entity;
				if (((previousValue != value) 
							|| (this._PHUONGTIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHUONGTIEN.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._PHUONGTIEN.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._MaPT = value.MaPT;
					}
					else
					{
						this._MaPT = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHUONGTIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DATTOURs(DATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_DATTOURs(DATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
	}
}
#pragma warning restore 1591
